/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface PacsCommandResult {
  success: boolean
  exitCode: number
  stdout: string
  stderr: string
}

/** Verifies basic connectivity to the PACS server with a DICOM echo request. */
export declare function pacsConnect(options: PacsConnectionOptions): boolean

export interface PacsConnectionOptions {
  host: string
  port: number
  callingAet?: string
  calledAet?: string
  timeoutSec?: number
}

/** Downloads matching patients, studies, or series directly into the resolved output subdirectory. */
export declare function pacsDownload(options: PacsDownloadOptions): PacsDownloadResult

export interface PacsDownloadOptions {
  host: string
  port: number
  localPort: number
  level: string
  queryModel?: string
  keys: Array<string>
  outputDir: string
  callingAet?: string
  calledAet?: string
  timeoutSec?: number
}

export interface PacsDownloadResult {
  success: boolean
  exitCode: number
  stdout: string
  stderr: string
  downloadedFiles: Array<string>
}

/** Executes a C-FIND query and returns parsed DICOM records from the PACS server. */
export declare function pacsSearch(options: PacsSearchOptions): PacsSearchResult

export interface PacsSearchField {
  tag: string
  vr: string
  keyword: string
  value: string
}

export interface PacsSearchOptions {
  host: string
  port: number
  level: string
  queryModel?: string
  template?: string
  keys?: Array<string>
  callingAet?: string
  calledAet?: string
  timeoutSec?: number
}

export interface PacsSearchRecord {
  fields: Array<PacsSearchField>
}

export interface PacsSearchResult {
  success: boolean
  exitCode: number
  stdout: string
  stderr: string
  records: Array<PacsSearchRecord>
  recordCount: number
}

/** Uploads one or more local DICOM files to the PACS server with C-STORE. */
export declare function pacsUpload(options: PacsUploadOptions): PacsCommandResult

export interface PacsUploadOptions {
  host: string
  port: number
  filePaths: Array<string>
  recursive?: boolean
  callingAet?: string
  calledAet?: string
  timeoutSec?: number
}
